type T_FieldContent = {
  value: string;
  format: string;
  processed: string;
};

type T_VarianStyles = {
  entity_type: any[];
  entity_bundle: any[];
  nid: any[];
  uuid: any[];
  vid: any[];
  langcode: any[];
  type: any[];
  revision_timestamp: any[];
  revision_uid: any[];
  status: any[];
  uid: any[];
  title: any[];
  created: any[];
  changed: any[];
  promote: any[];
  sticky: any[];
  default_langcode: any[];
  revision_translation_affected: any[];
  path: any[];
  content_translation_source: any[];
  content_translation_outdated: any[];
  field_key: Array<{ value: string }>;
};

type T_FieldMediaImage = {
  entity_type: any[];
  entity_bundle: any[];
  fid: any[];
  uuid: any[];
  langcode: any[];
  uid: any[];
  filename: any[];
  uri: Array<{ value: string; url: string }>;
  filemime: any[];
  filesize: any[];
  status: any[];
  created: any[];
  changed: any[];
};

type T_FieldImage = {
  entity_type: any[];
  entity_bundle: any[];
  mid: any[];
  uuid: any[];
  vid: any[];
  langcode: any[];
  bundle: any[];
  revision_created: any[];
  revision_user: any[];
  status: any[];
  uid: any[];
  name: any[];
  thumbnail: Array<T_FieldMediaImage>;
  created: any[];
  changed: any[];
  default_langcode: any[];
  revision_translation_affected: any[];
  path: Array<{ alias: any }>;
  field_media_image: any[];
};

type T_FieldColumnChild = {
  entity_type: any[];
  entity_bundle: any[];
  id: any[];
  uuid: Array<{ value: string }>;
  parent_id: any[];
  parent_type: any[];
  parent_field_name: any[];
  content_translation_source: any[];
  content_translation_outdated: any[];
  content_translation_changed: any[];
  field_alignment: any[];
  field_content: Array<{ value: string }>;
  field_icon_cta_style: any[];
  field_image: Array<T_FieldImage>;
  field_maximum_lines: any[];
  field_primary_cta: any[];
  field_title: Array<{ value: string }>;
};

type T_FieldColumn = {
  entity_type: any[];
  entity_bundle: Array<{ value: string }>;
  id: Array<{ value: number }>;
  uuid: Array<{ value: string }>;
  parent_id: Array<{ value: string }>;
  parent_type: any[];
  parent_field_name: any[];
  content_translation_source: any[];
  content_translation_outdated: any[];
  content_translation_changed: any[];
  field_alignment: any[];
  field_content: Array<T_FieldContent>;
  field_image: Array<T_FieldImage>;
  field_second_image: Array<T_FieldImage>;
  field_maximum_lines: Array<{ value: any[] }>;
  field_primary_cta: Array<{ uri: string; full_url: string; title: string }>;
  field_column?: Array<T_FieldColumnChild>;
  field_title: Array<{ value: string }>;
  field_subtitle: Array<{ value: string }>;
  field_column_per_row: any[];
  field_column_reversed_on_mobile: any[];
  field_container: any[];
  field_formatted_title: any[];
  field_margin_left: any[];
  field_note: Array<{ value: string }>;
  field_title_alignment: any[];
  field_web_variant_styles: any[];
  column_count: any[];
  field_paragraphs: Array<T_FieldColumnChild>;
};

export type T_Section = {
  entity_type: any[];
  entity_bundle: any[];
  id: any[];
  uuid: any[];
  revision_id: any[];
  langcode: any[];
  type: any[];
  status: any[];
  created: any[];
  parent_id: any[];
  parent_type: any[];
  parent_field_name: any[];
  behavior_settings: any[];
  default_langcode: any[];
  revision_translation_affected: any[];
  content_translation_source: any[];
  content_translation_outdated: any[];
  content_translation_changed: any[];
  field_column: Array<T_FieldColumn>;
  field_column_per_row: any[];
  field_column_reversed_on_mobile: any[];
  field_container: any[];
  field_content: Array<T_FieldContent>;
  field_formatted_title: Array<T_FieldContent>;
  field_image: Array<T_FieldImage>;
  field_margin_left: any[];
  field_note: Array<{ value: string }>;
  field_primary_cta: Array<{ uri: string; title: string; full_url: string }>;
  field_title_alignment: any[];
  field_web_variant_styles: Array<T_VarianStyles>;
  column_count: any[];
};
