export const WIDGET_VARIANT = {
  variant01: 'div_text_both_side_menu_01',
  variant02: 'div_two_banners_02',
  variant03: 'div_menu_center_01',
  variant04: 'div_overflow_banners_01',
  variant05: 'div_wm_card_01',
  variant06: 'carousel_video_01',
  variant07: 'div_menu_center_02',
  variant08: 'div_card_02',
  variant09: 'div_lounge',
  variant10: 'insight',
  variant11: 'article',
  variant12: 'program',
  variant13: 'div_menu_center_02a',
  variant14: 'div_menu_center_03',
  variant15: 'div_menu_center_03a',
  variant16: 'div_card_01',
  variant17: 'div menu center 02b',
  variant18: 'div_card_03',
  variant19: 'section_card_center_2',
  variant20: 'div_requirement_box',
  variant21: 'div_card_04',
};

export const API_BASE_URL = 'https://admin-bri-corpsite.dev-kjt.id';
