import { parseHTMLToReact } from '@/lib/functions/global/htmlParser';
import React from 'react';

const htmlString = `<p style="text-align: center;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><strong style="font-family: Gotham-Bold;"><span style="font-family: Calibri, sans-serif;">Kebijakan Privasi Umum untuk Layanan BRI</span></strong></p>
<p style="text-align: center;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">(Efektif berlaku sejak tanggal 15 April 2021)</strong></span></p>
<p style="text-align: center;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Terakhir diperbarui pada ( 15 April 2021 )</span></p>
<p style="text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">PT Bank Rakyat Indonesia (Persero) (&quot;<strong style="font-family: Gotham-Bold;">BRI&quot;</strong>) sepenuhnya menyadari bahwa data pribadi merupakan aset terpenting bagi Anda, sehingga BRI sangat menghargai kerahasiaan dan perlindungan terhadap data pribadi Anda terkait dengan penggunaan layanan poduk dan/atau jasa perbankan BRI.</span></p>
<br/>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Keamanan, kenyamanan, serta privasi Anda merupakan prioritas bagi BRI. BRI menerapkan kebijakan dan praktik terbaik yang bertujuan untuk menjaga dan memelihara privasi serta keamanan data pribadi Anda, sesuai peraturan Perlindungan Data Pribadi, untuk pemosesan data terkait dengan penggunaan layanan produk dan/atau jasa perbankan BRI <br/>(&quot;<strong style="font-family: Gotham-Bold;">Kebijakan Privasi</strong>&quot;)</span></p>
<br/></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI selalu meningkatkan layanan kami kepada Anda dan senantiasa melakukan pembaruan layanan demi untuk melindungi privasi dan keamanan data pribadi Anda sebagai nasabah kami.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">I. Tujuan dan Ruang Lingkup Kebijakan Privasi</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Kebijakan Privasi ini mengatur mengenai kebijakan-kebijakan dan praktik-praktik yang diterapkan oleh BRI dalam memperoleh, memperbaiki, memperbarui, menyebarluaskan, menampilkan, mengumumkan, mengalihkan, mengungkapkan, menghapuskan, dan memusnahkan (untuk selanjutnya disebut &quot;<strong style="font-family: Gotham-Bold;">Pemrosesan&quot;) data pribadi Anda sehubung dengan penggunaan layanan produk Anda dengan penggunaan layanan produk dan/atau jasa perbankan BRI, meliputi:</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="1" style="list-style-type: lower-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Jasa perbankan dari BRI meliputi Simpanan, Pinjaman dan Layanan Perbankan lainnya termasuk namun tidak terbatas pada produk investasi, Kartu Kredit<strong style="font-family: Gotham-Bold;">,&nbsp;</strong><em>Internet Banking</em><strong style="font-family: Gotham-Bold;">,</strong> Produk Trade Finance, Layanan BRILink dan Layanan Perbankan BRI lainnya.</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Situs<em>&nbsp;web</em>, fitur, aplikasi, media sosial, atau bentuk media komunikasi lainnya yang disediakan atau digunakan oleh BRI.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">(seluruhnya kemudian disebut &quot;<strong style="font-family: Gotham-Bold;">Layanan</strong>&quot;)</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Selanjutnya, Kebijakan Privasi ini berlaku untuk semua pemilik data Pribadi (Subyek Data), yang terkait dengan penggunaan layanan produk dan/atau jasa perbankan BRI.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">(seluruhnya kemudian disebut <strong style="font-family: Gotham-Bold;">&quot;Anda&quot;)</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">II. Tujuan Pemrosesan Data Pribadi</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Dalam melakukan Pemrosesan data pribadi Anda, BRI memiliki tujuan sebagai berikut:</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="1" style="list-style-type: lower-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk menjalankan prinsip<em>&nbsp;Know Your Customer</em> (KYC) dan memeberikan personalisasi kepada Anda terhadap penggunaan Layanan yang disediakan oleh BRI;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk menjalankan mandat peraturan perundang-undangan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk menjalankan penyelesaian masalah terkait akses terhadap Layanan (<em>troubleshoot</em>)</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk kebutuhan pemasaran dari layanan dan produk yang ditawarkanoleh BRI, hal ini termasuk seperti mengirimkan promosi, produk baru, berita, survei, pembaruan terkait layanan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk mengevaluasi dan memperbarui fitur Layanan BRI dari waktu ke waktu;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk kebutuhan pemrosesan Data Pribadi guna menghasilkan data profil Anda;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk kepentingan<em>&nbsp;loyality programme</em> kepada Anda seperti <em>gift</em>, undian, dan sebagaimananya;dan</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk menawarkan iklan/promosi maupun penawaran dari pihak lain yang bekerja sama dengan BRI</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">III. Data Pribadi yang Diperoleh dan Dikumpulkan oleh BRI</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI memperoleh dan mengumpulkan informasi yang mengidentifikasi dan/atau dapat diidentifikasi secara tersendiri atau dikombinasi dengan informasi lainnya baik secara langsung maupun &nbsp;tidak langsung melalui sistem elektronik dan/atau non-elektronik yang terkait dengan informasi tersebut yang dalam hal ini terbatas pada Layanan (&quot;<strong style="font-family: Gotham-Bold;">Data Pribadi</strong>&quot;).</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Data Pribadi Anda yang dikumpulkan oleh BRI dapat diberikan oleh Anda secara langsung maupun dari pihak ketiga (seperti misalnya ketika Anda mendaftar atau menggunakan Layanan, ketika Anda menghubungi layanan pelanggan Call BRI). BRI akan mengumpulkan Data Pribadi Anda dalam berbagai bentuk dengan tujuan, termasuk yang diperkenankan oleh peraturan perundang-udangan yang berlaku di Republik Indonesia.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Data Pribadi Anda yang dikumpulkan dalam penyelenggaraan Layanan ini adalah:</span></p>
<ol start="1" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data Pribadi yang dibutuhkan oleh BRI untuk menyelenggarakan Layanan, meliputi Data Pribadi yang bersifat umum dan khusus, sebgai berikut:</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Data Umum:</strong></span></p>
<ol style="text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Nama lengkap;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Alamat tempat tinggal;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Tempat dan Tanggal lahir;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Jenis kelamin;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Kewarganegaraan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Nama Gadis Ibu Kandung;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Agama;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Pekerjaan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Pendidikan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Jabatan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Nomor Induk Kependudukan / Paspor / Kartu Induk Anak / Kartu Pelajar;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Nomor Handpone;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Alamat Email;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Nomor telepon kantor/rumah; dan/atau</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data Pribadi yang dikombinasikan untuk mengidentifikasi sesorang.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Data Khusus:</strong></span></p>
<ol style="text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">&nbsp;Data biometrik yang memungkinkan identifikasi unik terhadap individu namun tidak terbatas pada gambar wajah, sidik jari, rekaman pembicara;</strong></li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Data keunagan pribadi namun tidak terbatas seperti Penghasilan dan Nomor Wajib Pajak; dan/atau;</strong></li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Data lainnya sesuai dengan ketentuan peraturan perundang-undangan yang berlaku.</strong></li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Selain itu, sepanjang informasi lain, termasuk profil pribadi dan/atau tanda pengenal, yang terasosiasi atau tergabung dalam Data Pribadi, maka informasi tersebut juga merupakan Data Pribadi. Anda memiliki pilihan untuk memberikan Data Pribadi tambahan kepada BRI untuk kebutuhan personalisasi akun di luar yang telah disebutkan di atas.</span></p>
<ol start="2" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data penelusuran atas infromasi yang dikumpulkan ketika Anda menggunakan Layanan yang diberikan oleh BRI. Infromasi yang berkenaan dengan Data Pribadi Anda termasuk namun tidak terbatas pada:</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="1" style="list-style-type: decimal;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data pencarian, riwayat penelusuran (termasuk tanggal dan waktu yang terekam);</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Keterkaitan atau prefensi Anda yang dikumpulkan dari penggunaan Layanan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Foto, suara, kontak, daftar penggilan ataupun interaksi lainnya dalam Layanan yang diizinkan oleh Anda untuk diakses melalui perangkat yang Anda miliki. BRI tidak pernah memindai atau mengambil foto-foto pada album dan/atau kamera dalam perangkat Anda.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="3" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data Pribadi yang dibuat dan didapatkan dari hasil penggunaan layanan milik BRI, termasuk namun tidak terbatas pada:</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="1" style="text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data olahan teknis, seperti <em>mobile positioning</em>, penilaian lokasi, dan<em>&nbsp;profiling&nbsp;</em>lanjutan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">informasi tentang Data yang diperoleh dari aktifitas pemakaian layanan perbankan yang Anda akses, seperti pembayaran tagihan maupun pemrofilan dan segmentasi Anda;</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="4" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data Pribasi dari Grup Usaha BRI dan/atau pihak ketiga lainnya yang berpartisipasi bermitra dengan BRI atau mengadakan kerja sama dengan BRI.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">IV. Penampilan, Pengumuman, Pengalihan, Penyebarluasan dan Pengungkapan Data Pribadi</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI tidak akan menjual, menukar, menampilkan, mengumumkan, mengalihkan, menyebarluaskan, dan/atau mengungkapkan Data Pribadi dan informasi apapun yang berkaitan dengan nasabah, pengunjung, atau penggunaa Layanan BRI.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Anda bertanggung jawab untuk menjaga kerahasiaan detail Data Pribadi Anda dan harus selalu menjaga dan bertanggung jawab atas keamanan perangkat yang Anda gunkan untuk mengakses Layanan BRI.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Nasabah dengan ini mengakui, dan jika diwajibkan oleh peraturan Perlindungan Data Pribadi yang berlaku, secara tegas menyetujui bahwa Data Pribadi yang diperoleh dan dikumpulkan oleh BRI bersama dengan infromasi terkait transaksi yang relevan, dapat diungkapkan kepada lembaga pemerintah yang berwenang, ataupun pihak lain yang berwenang berdasarkan undang-undang atau perjanjian kerja sama, dalam hal:</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="1" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk kepentingan hukum yang berlaku dan/atau untuk menanggapi proses hukum yang sedang berjalan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk melindungi keselamatan BRI, keselamatan Anda atau keselamatan orang lain atau demi kepentingan yang sah dalam konteks:</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="1" style="list-style-type: lower-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Keamanan nasional;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Proses penegakan hukum;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Penyelenggarakan negara;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Kepentingan pengawasan sektor jasa keuangan, moneter, sistem pembayaran dan stabilitas sistem keunagan;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Agregat data yang pemrosesannya ditujukan guna kepentingan statistik dan penelitian ilmiah dalam rangka penyelenggaraan negara; dan/atau</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Keadaan darurat yang telah ditetapkan oleh Pemerintah.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="3" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk kepentingan audit internal dan/atau digital forensic atas tindak pidana atau pelanggaran peraturan atrau kebijakan di lingkungan BRI dan Perusahaan Afiliasi;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Jika diperlukan sehubungan dengan proses hukum yang diajukan terhadap BRI, pejabat, karyawan, afiliasi, atau vendor terkait;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Untuk menetapkan, melaksanakan, melindungi, mempertahankan, dan menegakkan hak-hak hukum BRI;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Dalam rangka Pemrosesan Data Pribadi dnegan perushaan afiliasi BRI, BRI hanya akan memberikannya dengan itikad baik dalam bentuk ringkasan atas dasar kepentingan yang sah di mata hukum. Dalam hal BRI melakukan Pemrosesan Data Pribadi yang membuka profil pribadi Anda, BRI akan melakukan upaya terbaik untuk melindungi privasi atas Data Pribadi Anda, yang dilaksanakan setelah dilakukannya penandatanganan perjanjian kerahasiaan, atau persetujuan tambahan dengan cara memberikan pemberitahuan kepada Anda sebelum Data Pribadi Anda diungkapkan kepada afiliasi BRI serta tunduk pada Kebijakan Privasi Anda diungkapkan kepada afiliasi BRI serta tunduk pada Kebijakan Privasi dan peraturan perundang-undangan yang berlaku, sehingga tetap dapat memastikan kerahasiaan Data Pribadi Anda; atau;</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Untuk melakukan pengungkapan Data Pribadi Anda kepada pihak ketika, dalam rangkat untuk memastikan BRI dapat memberikan Layanan kepada Anda dan membantu Pemerintah Negara Indonesia beserta institusi pendukungnya untuk pelaksanaan fungsi-fungsi Negara.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Pengungkapan ini dilakukan dengan mempertimbangkan aspek-aspek pengamanannya sehingga memastikan dalam proses pengungkapan tidak ada data-data yang disalahgunakan.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">V. Penyimpanan Data Pribadi</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI berkomitmen untuk menyimpan Data Pribadi Anda dengan perlindungan terbaik selama diperlukan untuk menyediakan Layanan ini. Sebagaian Data Pribadi Anda dapat pula dikelola, diproses, dan disimpan oleh pihak ketiga yang beekrja sama dengan BRI baik di wilayah Indonesia maupun di luar wilayah Republik Indonesia guna menjaga kinerja Layanan dengan tetap mematuhi kewajiban atas akses dan efektifitas pengawasan sesui hukum yang berlaku.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI akan menyimpan Data Pribadi sebgaimana disebutkan di atas sepanjang hal tersebut dibutuhkan untuk mencapai tujuan mengapa Data Pribasi tersebut dikumpulkan, ketika Anda masih menggunakan Layanan, atau sepanjang penyimpanan tersebut diharuskan atau diperkenankan sesuai dengan kebijakan retensi data milik BRI serta peraturan perundang-undangan yang berlaku di Republik Indonesia.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI dapat mentransfer Data Pribadi keluar Wilayah republik Indonesia selama hal tersebut diperlukan dalam rangka pelaksanaan Layanan Perbankan kepda nasabah (misalnya: layanan <em>remittance&nbsp;</em>, penerbitan instrumen pembiayaan perdagangan luar negri, dll).</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI akan berhenti untuk menyimpan Data Pribadi Anda, atau menghilangkan cara-cara yang dengan mana Data Pribadi Anda dapat diasosiasikan dengan Anda, segera setelah beralasan untuk berasumsi bahwa tujuan pengumpulan Data Pribadi tersebut tidak lagi terpenuhi dengan penyimpanan Data Pribadi terkait dan penyimpanan tidak lagi diperlukan untuk tujuan hukum, dan bisnis.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">VI. Akses ke Data Pribadi Anda</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI berkomitmen untuk memenuhi hak Anda untuk mengakses Data Pribadi Anda yang dikumpulkan dan diproses oleh BRI. Dalam memenuhi permintaan akses ke data pribada Anda, BRI dapat menolak permintaan anda apabila BRI menemukan bahwa permintaan ke Data Pribadi Anda memenuhi salah satu atau beberapa kondisi, berikut ini;</span></p>
<ol start="1" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Membahayakan keamanan atau kesehatan fisik atau kesehatan mental Pemilik Data Pribadi dan/atau orang lain;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Berdampak pada pengungkapan data Pribadi milik orang lain; dan/atau;</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Bertentangan dengan kepentingan pertahanan dan keamanan nasional.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Untuk infromasi lebih lanjut terkait dengan permintaan akses data pribadi Anda, Anda dapat menghubingi saluran komunikasi yang tersedua berdasarkan Kebijakan Privasi ini.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">VII. Perbaikan dan Pembaruan Data Pribadi Anda</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Dalam hal Anda menemukan kekeliruan yang ditampilkan mengenai Data pribadi Anda dikarenakan ketidakakuratan atau diperlukan dilakukan pembaruan atas Data Pribadi Anda, maka Anda dapat meminta kepada BRI untuk memperbaiki, melengkapi dan/atau memperbarui Data Pribadi Anda yang berada dalam pengelolaan BRI, dengan menghubungi saluran komunikasi yang tersedia berdasarkan Kebijakan Privasi ini. Dalam hal terdapat ketidakakuratan dalam pemberian data pribadi dari Subyek Data, BRI berhak menghentikan layanan dan/atau transaksi berdasarkan pengetahuan dan pertimbangan Bank.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Kami menghimbau Anda untuk turut berperan aktif memastikan keakuratan dan pembaruan Data Pribadi Anda dari waktu ke waktu.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">VIII. Penghapusan dan Pemusnahan Data Pribadi</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Sesuai dengan peraturan perundang-undangan yang berlaku atau kebijakan retensi data milik BRI atau atas permintaan/permohonan Anda, BRI dapat menghapus dan/atau memusnahkan Data Pribadi Anda dari sistem (<em>right to erase</em>) agar data tersebut tidak lagi mengidentifikasi Anda, kecuali dalam hal:</span></p>
<ol start="1" style="list-style-type: upper-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Apabila perlu menyimpan Data Pribadi untuk memenuhi kewajiban hukum, keperluan pembuktian di kemudian hari, pajak, audit, dan akuntasi, BRI akan menyampaikan Dara Pribadi yang diperlukan selama Anda menggunakan layanan milik BRI atau sesuai jangka waktu yang disyaratkan oleh peraturan perundang-undangan yang berlaku; dan/atau</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Data Pribadi dalam Data Pribadi masih berapa dalam periode retensi berdasarkan peraturan perundang-undangan yang berlaku.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Perihal keperluan pemusnahan Data pribadi Anda dari sistem (<em>right to erase</em>), diperlukan permohonan tertulis yang diajukan oleh Anda kepada Kantor Pusat BRI agar kami dapat memusnahkan Data Pribadi dalam sistem milik BRI.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">IX. Keamanan data Pribadi</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Kerahasiaan Data Pribadi Anda adalah hal yang terpenting bagi BRI. BRI berkomitmen untuk memberlakukan upaya terbaiknya untuk melindungi dan mengamankan Data Pribadi Anda dari akses pengumpulan, pemgolahan, penganalisasisan, penyimpanan, pengungkapan, perbaikan dan penghapusan oleh pihak-pihak yang tidak berwenang.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Dalam hal terjadi akses dan kegiatan ilegal atas kerahasiaan Informasi Pribadi Anda yang berada di luar kendali BRI, BRI akan segara memberitahukan kepada Anda pada kesempatan pertama sehingga Anda dapat menggurangi resiko yang timbul atas hal tersebut.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Anda bertanggung jawab untuk menjaga kerahasiaan detil Data Pribadi Anda, termasuk informasi mengenai<em>&nbsp;username, password, email&nbsp;</em>maupun OTP kepada siapapun dan untuk selalu menjaga dan bertanggung jawab atas keamanan perangkat yang Anda gunakan.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">X. Pengakuan dan Persetujuan</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Kebijakan Privasi ini dapat diubah dan/atau diperbarui dari waktu ke waktu. BRI menyarankan kepada Anda agar selalu membaca secara seksama dan memeriksa halaman ini dari waktu ke waktu untuk mengetahui perubahan apapun yang ditimbulkan olehnya.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Anda dapat menarik persetujuan Anda terhadap setiap atau seluruh pengumpulan, penggunaan, penggungkapan Data Pribadi Anda pada setiap waktu dengan memberikan pemberitahuan tertulis yang beralasan ke kontak yang tertera di bawah ini.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Bergantung pada keadaan dan sifat dari persetujuan yang Anda tarik, Anda harus memahami dan mengakui bahwa BRI berwenang untuk memenuhi atau tidak memenuhi permintaan penarikan persetujuan tersebut, maka anda tidak lagi dapat menggunakan Layanan. Penarikan persetujuan oleh Anda dapat berakibat pada pernghentian akun Anda atau hubungan kontraktual Anda dengan BRI yang terkait, di mana semua hak dan kewajiban yang dimiliki masing-maisng pihak masih sepenuhnya dilindungi.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">XI. Pengaturan Layanan</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Anda dapat memilih untuk tidak menerima layanan pemasaran, pengiklanan, atau aktivitas lainnya yang terkait dengan pengolahan Data Pribadi di atas dengan menghubungi BRI melalui detil kontak yang tersedia di bawah pemberitahuan ini atau melalui mekanisme lain yang disiapkan oleh masing-masing Layanan kami. Mohon diperhatinkan, jika Anda memilih untuk tidak menerima satu Layanan, BRI masih berhak untuk mengirimi Anda pesan terkait layanan BRI, untuk Layanan lainnya yang Anda gunakan.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">XII. Bahasa</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Kebijakan Privasi ini disusun dan diterbitkan dalam Bahasa Inggris dan Bahasa Indonesia. Anda dapat menemukan bahasa yang berbeda untuk kebijakan privasi ini ketika Anda mengganti pengaturan bahasa di situs web atau aplikasi BRI. Jika terjadi ketidaksesuaian antara kedua bahasa ini, versi bahasa Indonesia yang berlaku.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">XIII. Hubungi Kami</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Jika Anda memiliki pertanyaan tentang Kebijakan Privasi ini, silahkan hubungi layanan pelanggan kami melalui informasi kontak berikut:</strong></span></p>
<ul style="text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Call Center</strong>: 14017/1500 017</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Email:&nbsp;</strong>callbri@bri.co.id</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">FB Messenger :&nbsp;</strong>BANK BRI</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Whatsapp:&nbsp;</strong>08121214017</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Telegram:&nbsp;</strong>User@kontakbri / Nomor 08121214017</li>
</ul>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Pengaman</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Brikut ini adalah kebijakan dan praktek yang dilakukan PT Bank Rakyat Indonesia, Tbk (&quot;BRI&quot;) untuk menunjukan komitmen BRI di dalam menjaga dan memelihara keamanan Anda pada saat Anda mengunjungi situs dan www.bri.co.id.</span></p>
<ol start="1" style="list-style-type: lower-roman;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Sistem Pengamanan</strong></li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">BRI menggunakan 2 (dua) lapis sistem pengamanan untuk melindungi akses dan transaksi Anda di www.bri.co.id yaitu :</strong></span></p>
<ol start="1" style="list-style-type: lower-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Secure Socket Layer (&quot;SSL&quot;)</strong></li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">SSL adalah teknologi pengamanan yang &apos;mengacak&apos; jalur&apos; antar komputer sehingga tidak dapat dibaca oleh pihak lain.</strong></span></p>
<ol start="2" style="list-style-type: lower-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">User ID dan password untuk administrator situs www.bri.co.id</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Karena banyaknya variasi browser internet yang ada, sulit untuk menyediakan layanan yang mengikuti keamanan masing-masing browser. Saat ini BRI hanya menyediakan sarana www.bri.co.id yang lebih cocok diakses dengan menggunakan Microsoft Internet Explorer versi 10 ke atas, Mozilla Firefox versi 2.0.0 ke atas atau Safari versi 4.0.3 ke atas. BRI mohon maaf atas ketidaknyamanan ini.</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="2" style="list-style-type: lower-roman;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Proteksi Komunikasi Situs www.bri.co.id</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">BRI menggunakan teknologi enkripsi Secure Socket Layer (SSL) 256 bit untuk memproteksi komunikasi antara komputer Anda dan server BRI selama Anda mengakses www.bri.co.id</span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">Untuk memastikan proteksi komunikasi selama Anda mengakses www.bri.co.id, Anda dapat melakukan hal-hal sebagai berikut:</span></p>
<ol start="1" style="list-style-type: lower-alpha;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Periksa sertifikat SSL secara teratur untuk memastikan bahwa Anda menerima sertifikat SSL yang sah yang telah terdaftar untuk https://www.bri.co.id</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Apabila Anda menerima pesan yang menjelaskan bahwa sertifikat tidak sah, dimohon Anda tidak melanjutkan akses www.bri.co.id.</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Pastikan bahwa Anda telah mengetik alamt yang benar yaitu https://ww.bri.co.id</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Pastikan bahwa pada browser Anda terdapat gambar gembok/kunci yang mengidentifikasikan bahwa yang Anda akses saat dienkrispi dengan menggunakan SSL. Jika Anda melakukan pertukaran data informasi pribadi.</li>
    <li style="text-align: justify; font-family: Calibri, sans-serif;">Sebaiknya Anda tidak mengakses di jaringan yang tidak pasti keamanannya.</li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;">&nbsp;</span></p>
<ol start="3" style="list-style-type: lower-roman;text-align: start;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;">
    <li style="text-align: justify; font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Situs BRI</strong></li>
</ol>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Di dalam situs BRI, BRI menyediakan URL link ke situs lain yang tidak dikontrol oleh BRI. BRI tidak bertanggung jawab atas isi dan keamanan dari situs tersebut. Jika Anda mengakses situs tersbtu, silahkan memeriksa kebijakan privasi dan mengamanan mereka.</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><span style="font-family: Calibri, sans-serif;"><strong style="font-family: Gotham-Bold;">Dalam hal Anda mengakses situs melalui URL link dari situs lain, pastikan kebenaran alamat yang Anda akses yaitu https://www.bri.co.id</strong></span></p>
<p style="text-align: justify;color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);font-size: 14px;font-family: Gotham-Book-Regular;"><strong style="font-family: Gotham-Bold;"><span style="font-family: Calibri, sans-serif;">BRI dapat mengubah kebijakan privasi dan informasi pengamanan ini setiap saat untuk tetap menyesuaikan dengan situasi dan teknologi terbaru. Anda selalu dapat meninjau informasi dan kebijakan privasi BRI yang terbaru di https://www.bri.co.id.</span></strong></p>`;

export default function CardVariant11() {
  return (
    <div className="w-full p-5 flex justify-center">
      <div className="w-full md:w-10/12 lg:w-8/12 xl:w-7/12 font-normal text-sm leading-5 ">
        {parseHTMLToReact(htmlString)}
      </div>
    </div>
  );
}
